apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflixcloneapp-deployment
  labels:
    app: netflixcloneapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflixcloneapp
  template:
    metadata:
      labels:
        app: netflixcloneapp
    spec:
      containers:
        - name: netflixcloneapp
          image: btppavan/netflix:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: netflixcloneapp-ssvc
  labels:
    app: netflixcloneapp
spec:
  type: LoadBalancer  # Service type set to LoadBalancer
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the service
      targetPort: 80  # Port on which the application is running inside the container
  selector:
    app: netflixcloneapp
